Fixing automatic builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,83 +12,90 @@ on:
     # paths: ['app/**']
 
   # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch: {}
+  workflow_dispatch: { }
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout branch
-      uses: actions/checkout@v4
+      - name: Checkout branch
+        uses: actions/checkout@v4
 
-    - name: Setup JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'oracle'
-      
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+      - name: Setup JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'oracle'
 
-    - name: Setup Android SDK
-      uses: android-actions/setup-android@v3
-      with:
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+
+      - name: Setup Android SDK
+        uses: android-actions/setup-android@v3
+        with:
           log-accepted-android-sdk-licenses: false
 
-    - name: Setup google-services.json
-      env:
-        google_service: ${{ secrets.GOOGLE_SERVICES_JSON }}
-      run: echo $google_service > /home/runner/work/UpChat/UpChat/app/google-services.json
+      - name: Setup google-services.json
+        env:
+          google_service: ${{ secrets.GOOGLE_SERVICES_JSON }}
+        run: echo $google_service > /home/runner/work/UpChat/UpChat/app/google-services.json
 
-    - name: Cleaning builds
-      run: ./gradlew clean
+      - name: Cleaning builds
+        run: ./gradlew clean
 
-    - name: Testing
-      run: ./gradlew check
+      - name: Testing
+        run: ./gradlew check
 
-    - name: Building Release apk
-      run: echo "./gradlew assembleRelease --stacktrace"
+      - name: Building Release apk
+        run: echo "./gradlew assembleRelease --stacktrace"
 
-    - name: Building Bundle Release
-      run: echo "./gradlew bundleRelease --stacktrace"
+      - name: Building Bundle Release
+        run: ./gradlew bundleRelease --stacktrace
 
-    - name: Get aab build path
-      id: releaseAab
-      run: |
-        aabfile=$(find app/build/outputs/bundle/release -name "*.aab" -print -quit)
-        echo "aabfile=$aabfile" >> $GITHUB_ENV
-        echo "aabfile=$aabfile" >> $GITHUB_OUTPUT
+      - name: Verify Bundle Release Directory
+        run: |
+          if [ ! -d app/build/outputs/bundle/release ]; then
+            echo "Error: Bundle release directory does not exist."
+            exit 1
+          fi
 
-    - name: Get apk build path
-      id: releaseApk
-      run: |
-        apkfile=$(find app/build/outputs/apk/release -name "*.apk" -print -quit)
-        echo "apkfile=$apkfile" >> $GITHUB_ENV
-        echo "apkfile=$apkfile" >> $GITHUB_OUTPUT
+      - name: Get aab build path
+        id: releaseAab
+        run: |
+          aabfile=$(find app/build/outputs/bundle/release -name "*.aab" -print -quit)
+          echo "aabfile=$aabfile" >> $GITHUB_ENV
+          echo "aabfile=$aabfile" >> $GITHUB_OUTPUT
 
-    - name: Upload AAB Release Build to Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: AAB
-        path: ${{ steps.releaseAab.outputs.aabfile }}
-        if-no-files-found: ignore
-        compression-level: 0
+      - name: Get apk build path
+        id: releaseApk
+        run: |
+          apkfile=$(find app/build/outputs/apk/release -name "*.apk" -print -quit)
+          echo "apkfile=$apkfile" >> $GITHUB_ENV
+          echo "apkfile=$apkfile" >> $GITHUB_OUTPUT
 
-    - name: Upload APK Release Build to Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: APK
-        path: ${{ steps.releaseApk.outputs.apkfile }}
-        if-no-files-found: error
-        compression-level: 0
+      - name: Upload AAB Release Build to Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: AAB
+          path: ${{ steps.releaseAab.outputs.aabfile }}
+          if-no-files-found: ignore
+          compression-level: 0
 
-    - run: mv ${{ github.workspace }}/app/build/reports/lint-results-debug.html ./lint-results-debug.html
+      - name: Upload APK Release Build to Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: APK
+          path: ${{ steps.releaseApk.outputs.apkfile }}
+          if-no-files-found: error
+          compression-level: 0
 
-    - name: Upload Check Results to Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: Check_Result
-        path: ./lint-results-debug.html
-        if-no-files-found: ignore
-        compression-level: 0
+      - run: mv ${{ github.workspace }}/app/build/reports/lint-results-debug.html ./lint-results-debug.html
+
+      - name: Upload Check Results to Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: Check_Result
+          path: ./lint-results-debug.html
+          if-no-files-found: ignore
+          compression-level: 0
